apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dlrb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0013-tenant/tkrw-pr712-0075-0013-app/devfile-sample-dlrb@sha256:bc293c99821ec2722cd828547bee07bbd8c1d3804a669b6a7410677a7288d0b9
        name: my-nodejs
        resources: {}
status: {}
